"""fix deleted_at in pulibc

Revision ID: 0fbd057695c7
Revises: 9e9917e041f9
Create Date: 2026-03-13 14:44:58.810671

"""

from typing import Union
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "0fbd057695c7"
down_revision: str | Sequence[str] | None = "9e9917e041f9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
