"""replace public model

Revision ID: 9e9917e041f9
Revises: bba42f6d8a2b
Create Date: 2026-03-05 16:43:40.831328

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e9917e041f9"
down_revision: str | Sequence[str] | None = "bba42f6d8a2b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "likes",
        sa.Column("public_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["public_id"],
            ["public.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("public_id", "user_id"),
    )
    op.add_column("public", sa.Column("author_id", sa.Integer(), nullable=False))
    op.drop_constraint(op.f("public_owner_id_fkey"), "public", type_="foreignkey")
    op.create_foreign_key(None, "public", "users", ["author_id"], ["id"])
    op.drop_column("public", "owner_id")
    op.drop_column("public", "like")
    op.drop_column("public", "dislike")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "public",
        sa.Column("dislike", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "public", sa.Column("like", sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "public",
        sa.Column("owner_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "public", type_="foreignkey")
    op.create_foreign_key(
        op.f("public_owner_id_fkey"), "public", "users", ["owner_id"], ["id"]
    )
    op.drop_column("public", "author_id")
    op.drop_table("likes")
    # ### end Alembic commands ###
